### ISSUE TITLE
Use `omega` instead of `linarith` in the `scalar_tac` tactic

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/aeneas#105]
The `omega` tactic seems more performant than `linarith`, so it is worth at least experimenting. In particular, I wonder how good it is at reasoning about goals which contain both `Nat` and `Int` values.

**Comment by zhassan-aws** [comment]
That would be great. As of [lean v4.7.0](https://github.com/leanprover/lean4/releases/tag/v4.7.0) (released a few hours ago), `omega` is available without any imports.
