### ISSUE TITLE
Update the CI to check there is no diff in the generated files

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/aeneas#128]
The CI should already do that, but it seems it doesn't work.
For instance, the CI for https://github.com/AeneasVerif/aeneas/pull/125 should have failed.

**Comment by Nadrieril** [comment]
What's the easiest way to detect which files are generated? I'd like to run something like `make clean-generated-files` in CI to be sure we regenerate everything well.

**Comment by Nadrieril** [comment]
Oh, I can grep for `THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS` :D

This reveals that a number of files in the repo are not in fact regenerated, in particular a bunch of `hol4` ones.
