### ISSUE TITLE
Easy installation recipes

### ISSUE THREAD

**Issue by RaitoBezarius** [AeneasVerif/aeneas#144]
We discussed earlier the creation of an easy installation recipe to work using Aeneas.

cc @Nadrieril @sonmarcho 

Re: discussion on static binaries, currently, here are the results:
```
❯ ldd result/bin/aeneas 
	linux-vdso.so.1 (0x00007ffc46deb000)
	libpthread.so.0 => /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libpthread.so.0 (0x00007f9812a07000)
	libgmp.so.10 => /nix/store/s3s7gv33p88kzbgki2bprg2a1nc7jnf8-gmp-with-cxx-6.3.0/lib/libgmp.so.10 (0x00007f9812964000)
	libm.so.6 => /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libm.so.6 (0x00007f9812884000)
	libc.so.6 => /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6 (0x00007f981269c000)
	/nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/ld-linux-x86-64.so.2 => /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib64/ld-linux-x86-64.so.2 (0x00007f9812a0e000)
```

```
❯ ldd result/bin/charon
	linux-vdso.so.1 (0x00007fffddee1000)
	libgcc_s.so.1 => /nix/store/myw67gkgayf3s2mniij7zwd79lxy8v0k-gcc-12.3.0-lib/lib/libgcc_s.so.1 (0x00007f223c27f000)
	libc.so.6 => /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6 (0x00007f223c097000)
	/nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/ld-linux-x86-64.so.2 => /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib64/ld-linux-x86-64.so.2 (0x00007f223c545000)
```

**Comment by Nadrieril** [comment]
Found [here](https://users.rust-lang.org/t/including-rustc-driver-forces-dynamic-libstd-linking/44787/2):

> `rustc_driver` is only available as dylib. It is dynamically linked to `libstd`.

**Comment by Nadrieril** [comment]
The various `.so` files we need are installed by rustup when we ask for the `rustc-dev` and `llvm-tools-preview` components. So `cargo aeneas` should call to rustup to install the pinned toolchain + components we need, then provide `charon-driver` with the path to the `.so`s inside `~/.rustup`. In fact, `rustup run nightly-2023-06-02-x86_64-unknown-linux-gnu <command>` runs the command with the appropriate `LD_LIBRARY_PATH`, that's nice.

**Comment by sonmarcho** [comment]
We can consider this as done, right?

**Comment by Nadrieril** [comment]
Current state looks ok to me
