### ISSUE TITLE
Make test in aeneas repository does not work

### ISSUE THREAD

**Issue by BoltonBailey** [AeneasVerif/aeneas#163]
The instructions on running `make test` say:

> You can also use make test and make verify to run the tests, and check the generated files. As make test will run tests which use the Charon tests, you will need to regenerate the .llbc files. You have the following options:
> 
>     run make test in the Charon repository
>     run make test in the Aeneas repository
> 

Indeed, if I run `gmake test` in the Charon repository I get no errors. However, if I run in `aeneas` repository, I get

```
$ gmake test                                   
cd compiler && dune build
cd compiler && dune build aeneas.cmxs    
mkdir -p bin                           
cp -f compiler/_build/default/main.exe bin/aeneas
cp -f compiler/_build/default/main.exe bin/aeneas.cmxs
mkdir -p bin/backends/fstar
mkdir -p bin/backends/coq
cp -rf backends/fstar/*.fst* bin/backends/fstar/
cp -rf backends/coq/*.v bin/backends/coq/
cd compiler && dune build @doc
bin/aeneas ../charon/tests/llbc/no_nested_borrows.llbc -dest tests/fstar/misc -test-trans-units -backend fstar
File not found: ../charon/tests/llbc/no_nested_borrows.llbc
Aeneas: verification of Rust programs by translation to pure lambda calculus

Usage: bin/aeneas [OPTIONS] FILE
gmake: *** [Makefile:278: tfstar-no_nested_borrows] Error 1
```

which is an error.

**Comment by Nadrieril** [comment]
Hi, thanks for reporting that! This is known, today there's an implicit assumption that you cloned Charon and Aeneas into the same directory. We're working on fixing that
