### ISSUE TITLE
Add Negative Tests

### ISSUE THREAD

**Issue by R1kM** [AeneasVerif/aeneas#171]
Similarly to what is done in Charon, we should add negative tests to Aeneas, for instance to ensure to catch and test unsupported features.
One example is #166, where it would be good to ensure that the checks for mutually recursive traits are indeed satisfied, and that Aeneas fails as expected on the corresponding examples.

**Comment by Nadrieril** [comment]
Other example: https://github.com/AeneasVerif/aeneas/issues/190
