### ISSUE TITLE
Print the name pattern in the error message when a declaration has to be ignored because of an error

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/aeneas#190]
It happens that we can't extract a declaration *at all* and have to ignore it. For instance, if we encounter an error when translating the signature of a function, we ignore it and print the following message:
```
[ERROR] ... ERROR ...
[ERROR] Could not translate the function 'foo' because of previous error
```

It would be useful to add the name pattern (the Rust name identifying a definition) in the error message. This would be especially useful to add builtin support for external declarations which fail to extract.

**Comment by Nadrieril** [comment]
Fixed by https://github.com/AeneasVerif/aeneas/pull/199 but it would be nice to add a negative test for that when we get them
