### ISSUE TITLE
Hide rustc hash in paths

### ISSUE THREAD

**Issue by Nadrieril** [AeneasVerif/aeneas#193]
As can be seen in https://github.com/AeneasVerif/aeneas/pull/192, some paths in the output depend on the rustc version we used. This is unfortunate, we should probably hide those hashes.

**Comment by sonmarcho** [comment]
This is related: https://github.com/AeneasVerif/aeneas/issues/160

**Comment by Nadrieril** [comment]
Oh yeah :+1:
