### ISSUE TITLE
Aeneas still generate `as` variable names even though they are reserved keywords

### ISSUE THREAD

**Issue by RaitoBezarius** [AeneasVerif/aeneas#210]
Repro: https://github.com/RaitoBezarius/avl-verification/tree/avl

Things like:
```lean
let as ← AVLTreeSet.insert_rebalance_left_loop T OrdInst self.root
```

are still generated so far, even after https://github.com/AeneasVerif/aeneas/pull/146.

**Comment by RaitoBezarius** [comment]
Still an issue in https://github.com/AeneasVerif/aeneas/commit/3f07bf067fe725c2bc60b12139ff9cba13375c6a (main).

**Comment by sonmarcho** [comment]
Triggered by the AVL trees?

**Comment by sonmarcho** [comment]
(if yes I can reopen the issue)

**Comment by RaitoBezarius** [comment]
Argh, that might be related to me messing up my version of Charon/Aeneas actually, please ignore.
