### ISSUE TITLE
Aeneas' projectors in Lean can collide with structure functions

### ISSUE THREAD

**Issue by RaitoBezarius** [AeneasVerif/aeneas#211]
Consider:

```rust
struct AVLTree {
    height: usize
}

impl AVLTree {
    fn height(&self) -> usize { ... }
}
```

This will yield a Lean projector and a Lean function for `height`, those will collide.

cc @R1kM @sonmarcho

**Comment by sonmarcho** [comment]
This is extremely annoying. I'm not sure what the best thing to do is.

**Comment by RaitoBezarius** [comment]
In Lean, we could make better use of namespaces. We have the trait and the structure.

Multiple options:

- `AVLTree.Trait.height`
- `AVLTree.Projections.height`

Let the user "import" stuff and open namespaces for their usecases.

But that's my 2 cents.
