### ISSUE TITLE
Aeneas will emit monadic let binding code for infallible functions

### ISSUE THREAD

**Issue by RaitoBezarius** [AeneasVerif/aeneas#212]
Repro: https://github.com/RaitoBezarius/avl-verification/tree/avl

Observe that `Option.take`, `Option.isNone` and `core.mem.swap` are bound using monadic code to deal with Result-returning functions.

Observe that: https://github.com/AeneasVerif/aeneas/blob/ad9b5143618537de8377912f8c60cf6375737cb1/compiler/ExtractBuiltin.ml#L545-L550.

It seems that this block has no effect?

**Comment by sonmarcho** [comment]
We need to update the code because there is redundancy: you also need to add those around line 448.
I will update this file to prevent this kind of mistakes.

**Comment by RaitoBezarius** [comment]
Urgh… Sorry for that.
