### ISSUE TITLE
IF + function and WHILE after fails

### ISSUE THREAD

**Issue by vovunku** [AeneasVerif/aeneas#229]
Here an example, this builds without problems:
![image](https://github.com/AeneasVerif/aeneas/assets/33938211/b28e0f72-95f8-47af-8ed5-e783544befac)

But this will fail:

![image](https://github.com/AeneasVerif/aeneas/assets/33938211/189e1bef-327a-421d-85a3-09a793421de3)
![image](https://github.com/AeneasVerif/aeneas/assets/33938211/f98231d2-f4dc-4526-b604-40b4e6019367)

Example in code
```
fn bar() -> bool {
    return true;
}

fn foo<const N: usize>() -> (i64, i64) {
    if bar() || bar() {
        bar();
        return (1, 1);
    }
    let mut i = 0;
    while i < N {
    }
    (0, 0)
}
```

**Comment by sonmarcho** [comment]
I also don't manage to reproduce the bug.
