### ISSUE TITLE
`make setup-charon` can fail when the OID doesn't exist in Charon

### ISSUE THREAD

**Issue by RaitoBezarius** [AeneasVerif/aeneas#300]
When the Git object ID doesn't exist in Charon, `git checkout` will fail with an obscure error `$rev not in tree`.

The setup should pull or fetch that revision beforehand or recommend the user to do it.

**Comment by sonmarcho** [comment]
When does this get triggered?

**Comment by Nadrieril** [comment]
If we call `make setup-charon`, and the charon pin has moved forward, and the current clone of charon is too old to have that new commit. The fix is to add a `git fetch origin` before the `git checkout`.
