### ISSUE TITLE
Error on bitwise XOR assignment (^=) of an array index value

### ISSUE THREAD

**Issue by tenedor** [AeneasVerif/aeneas#391]
The following valid Rust code causes Aeneas to error. Switching the erroring line with the commented out equivalent line resolves the problem.

```rust
pub fn ex(a: u8) -> u8 {
    let mut temp = [0x01];
    temp[0] ^= a; // <-- ERROR
    // temp[0] = temp[0] ^ a;
    temp[0]
}
```

Aeneas: `[Error] Can not apply a projection to the ⊥ value`

**Comment by sonmarcho** [comment]
I do not have the error on my side - Aeneas generates the following (Lean) code:
```lean
def ex (a : U8) : Result U8 :=
  do
  let i ← Array.index_usize (Array.make 1#usize [ 1#u8 ]) 0#usize
  let temp ←
    Array.update_usize (Array.make 1#usize [ 1#u8 ]) 0#usize (i ^^^ a)
  Array.index_usize temp 0#usize
```

However, I fixed a similar issue recently - could you check whether you're using Aeneas' latest version?

**Comment by tenedor** [comment]
Ah, I'm also seeing this fixed on the latest Aeneas code. Nice work.
