### ISSUE TITLE
Match on integer produces invalid Lean

### ISSUE THREAD

**Issue by zhassan-aws** [AeneasVerif/aeneas#78]
The following Rust function:
```rust
fn foo(x: i32) -> bool {
    match x {
        0 => true,
        _ => false
    }
}
```
produces:
```lean
/- [match_i32::foo]:
   Source: 'src/main.rs', lines 1:0-1:22 -/
def foo (x : I32) : Result Bool :=
  match x with
  /-
  invalid pattern, constructor or constant marked with '[match_pattern]' expected
  -/
  | 0#i32 => Result.ret true
  | _ => Result.ret false
```
Lean complains about the `0#i32` with the error shown in the comment.

**Comment by zhassan-aws** [comment]
One workaround is to replace the `0#i32` with `{ val := 0, hmin := _, hmax := _ }`:
```lean
def foo (x : I32) : Result Bool :=
   match x with
  |  { val := 0, hmin := _, hmax := _ }  => Result.ret true
  | _ => Result.ret false
```

**Comment by sonmarcho** [comment]
Thanks for this! I hadn't thought of that.
It's still pretty ugly I think: I'm gonna see with the Lean people if there is a way of having a nicer syntax.

**Comment by sonmarcho** [comment]
This works, actually:
```lean
notation:65 a:65 "#scalar" => Scalar.mk a _ _

example {ty} (x : Scalar ty) : ℤ :=
  match x with
  | v#scalar => v
```

**Comment by sonmarcho** [comment]
I think I have a solution [here](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Different.20elaboration.20inside.2Foutside.20of.20match.20patterns/near/425455284).

**Comment by sonmarcho** [comment]
Fixed by https://github.com/AeneasVerif/aeneas/pull/82
